# Site settings
title: Seen
email: kpinksphoto@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Photography by Kerianne Pinkstaff
baseurl: "/kp-photo-website" # the subpath of your site, e.g. /blog/
url: "http://example.com" # the base hostname & protocol for your site
twitter_username:
github_username:
instagram_username:

# Build settings
markdown: kramdown

# Build a page for each gallery
page_gen:
  - data: 'galleries'
    template: 'gallery_page'
    name: 'name'
    dir: 'galleries'
