# Site settings
title: Seen
email: kpinksphoto@gmail.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.thevisiblefrequencies.com" # the base hostname & protocol for your site
twitter_username:
github_username:
instagram_username:

# Build settings
markdown: kramdown

exclude:
- README.md
- Gemfile
- Gemfile.lock

collections:
  galleries:
    output: true
