# Site settings
title: the visible frequencies
email: kerianne@thevisiblefrequencies.com
description: >
  Here's some light I caught. Welcome to my collection.<br>
  - Kerianne Pinkstaff
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.thevisiblefrequencies.com" # the base hostname & protocol for your site
twitter_username:
github_username:
instagram_username: thevisiblefrequencies

# Build settings
markdown: kramdown

exclude:
- CNAME
- Gemfile
- Gemfile.lock
- README.md
- LICENSE

collections:
  galleries:
    output: true
